### ISSUE TITLE
Invalid PGP key causes app to crash. 

### ISSUE THREAD

**Issue by glenn-sorrentino** [scidsg/hushline#319]
```
2024-04-04 13:28:32,464:DEBUG:Attempting to validate key: asdf
2024-04-04 13:28:32,469:ERROR:Error validating PGP key: unexpected EOF
2024-04-04 13:28:32,470:ERROR:Error: Could not build url for endpoint 'settings'. Did you mean 'settings.index' instead?
Traceback (most recent call last):
  File "/Users/glennsorrentino/Nextcloud/Git/hushline/venv/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennsorrentino/Nextcloud/Git/hushline/venv/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennsorrentino/Nextcloud/Git/hushline/venv/lib/python3.12/site-packages/flask_limiter/extension.py", line 1299, in __inner
    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennsorrentino/Nextcloud/Git/hushline/hushline/utils.py", line 20, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/glennsorrentino/Nextcloud/Git/hushline/hushline/settings.py", line 446, in update_pgp_key
    return redirect(url_for("settings"))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/glennsorrentino/Nextcloud/Git/hushline/venv/lib/python3.12/site-packages/flask/helpers.py", line 220, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennsorrentino/Nextcloud/Git/hushline/venv/lib/python3.12/site-packages/flask/app.py", line 1074, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennsorrentino/Nextcloud/Git/hushline/venv/lib/python3.12/site-packages/flask/app.py", line 1063, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/glennsorrentino/Nextcloud/Git/hushline/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 926, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'settings'. Did you mean 'settings.index' instead?
2024-04-04 13:28:32,477:INFO:127.0.0.1 - - [04/Apr/2024 13:28:32] "POST /settings/update_pgp_key HTTP/1.1" 500 -
```

**Comment by glenn-sorrentino** [comment]
Fixed locally and on beta site.

settings.py, Line 446.

```
- return redirect(url_for("settings"))
+ return redirect(url_for(".index"))
```
