### ISSUE TITLE
Crash on /settings/branding

### ISSUE THREAD

**Issue by micahflee** [scidsg/hushline#766]
I ran Hush Line from `main` using `make run`, logged in as an admin, and went to `/settings/branding`. It crashes with this error:

```
app-1           | 2024-11-25 18:27:26,495:INFO:172.19.0.1 - - [25/Nov/2024 18:27:26] "GET /settings/branding HTTP/1.1" 500 -
app-1           | Traceback (most recent call last):
app-1           |   File "/root/.cache/pypoetry/virtualenvs/hushline-9TtSrW0h-py3.12/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
app-1           |     return self.wsgi_app(environ, start_response)
app-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1           |   File "/root/.cache/pypoetry/virtualenvs/hushline-9TtSrW0h-py3.12/lib/python3.12/site-packages/flask/app.py", line 1476, in wsgi_app
app-1           |     response = self.handle_exception(e)
app-1           |                ^^^^^^^^^^^^^^^^^^^^^^^^
app-1           |   File "/root/.cache/pypoetry/virtualenvs/hushline-9TtSrW0h-py3.12/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
app-1           |     response = self.full_dispatch_request()
app-1           |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1           |   File "/root/.cache/pypoetry/virtualenvs/hushline-9TtSrW0h-py3.12/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
app-1           |     rv = self.handle_user_exception(e)
app-1           |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1           |   File "/root/.cache/pypoetry/virtualenvs/hushline-9TtSrW0h-py3.12/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
app-1           |     rv = self.dispatch_request()
app-1           |          ^^^^^^^^^^^^^^^^^^^^^^^
app-1           |   File "/root/.cache/pypoetry/virtualenvs/hushline-9TtSrW0h-py3.12/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
app-1           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
app-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1           |   File "/app/hushline/settings/__init__.py", line 538, in branding
app-1           |     return render_template(
app-1           |            ^^^^^^^^^^^^^^^^
app-1           |   File "/root/.cache/pypoetry/virtualenvs/hushline-9TtSrW0h-py3.12/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
app-1           |     return _render(app, template, context)
app-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1           |   File "/root/.cache/pypoetry/virtualenvs/hushline-9TtSrW0h-py3.12/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
app-1           |     rv = template.render(context)
app-1           |          ^^^^^^^^^^^^^^^^^^^^^^^^
app-1           |   File "/root/.cache/pypoetry/virtualenvs/hushline-9TtSrW0h-py3.12/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
app-1           |     self.environment.handle_exception()
app-1           |   File "/root/.cache/pypoetry/virtualenvs/hushline-9TtSrW0h-py3.12/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
app-1           |     raise rewrite_traceback_stack(source=source)
app-1           |   File "/app/hushline/templates/settings/branding.html", line 1, in top-level template code
app-1           |     {% extends "base.html" %}
app-1           |   File "/app/hushline/templates/base.html", line 171, in top-level template code
app-1           |     {% block content %}
app-1           |   File "/app/hushline/templates/settings/branding.html", line 10, in block 'content'
app-1           |     {% include "settings/nav.html" %}
app-1           |   File "/app/hushline/templates/settings/nav.html", line 1, in top-level template code
app-1           |     {% set aliases_enabled = alias_mode == AliasMode.ALWAYS or (alias_mode == AliasMode.PREMIUM and not user.is_free_tier) %}
app-1           |   File "/root/.cache/pypoetry/virtualenvs/hushline-9TtSrW0h-py3.12/lib/python3.12/site-packages/jinja2/environment.py", line 487, in getattr
app-1           |     return getattr(obj, attribute)
app-1           |            ^^^^^^^^^^^^^^^^^^^^^^^
app-1           | jinja2.exceptions.UndefinedError: 'user' is undefined
```

In `hushline/templates/settings/nav.html`, it uses `user` here:

```jinja2
{% set aliases_enabled = alias_mode == AliasMode.ALWAYS or (alias_mode == AliasMode.PREMIUM and not user.is_free_tier) %}
<div class="settings-tabs">
  <ul class="tab-list" role="tablist">
```

But it's not being passed into the template.

**Comment by micahflee** [comment]
I've hit this again and I think this has something to do with the following:

- being logged into an account with the branding settings page loaded
- somehow getting logged out (session cookie expiring or getting invalidated)
- refresh the page in this state

Basically, there's a mismatch where I think the route is getting executed and the template is displayed, but it shouldn't be because the user is not authenticated.

Because when I load / in a new tab, I'm not logged in.

**Comment by brassy-endomorph** [comment]
It's because the `user` object is no longer getting passed into the templates at all. You can trigger this for any users when the `ALIAS_MODE` is set to `premium` because it will cause the rightmost expression to evaluate.

We really need to refactor the login stuff because this is somewhat related.
